
name: Deploying

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  NODE_VERSION: '18.x'                # set this to the node version to use

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: npm install, build
      run: |
        npm install
        npm run build --if-present
        ls
#     - name: deploy
#       uses: D3rHase/rsync-deploy-action@v0.2
#       with:
#         HOST: ${{secrets.REMOTE_HOST}}                             # Remote server address / ip - Required: true
#         PORT: ${{secrets.REMOTE_PORT}}                             # Remote server port -  Default: 22 - Required: false
#         USER: ${{secrets.REMOTE_USER}}                             # Remote server user - Required: true
#         PRIVATE_SSH_KEY: ${{secrets.SSH_PRIVATE_KEY}}       # Private ssh key registered on the remote server - Required: true
#         REPOSITORY_PATH: ${{ vars.SOURCE }}       # Repository path of the file-s you want to upload - Default: * - Required: true
#         SERVER_PATH: ${{ vars.TARGET }}               # Server destination / path, where the file-s will be uploaded to - Default: ~/ - Required: false
    
    - name: ssh deploy
      # You may pin to the exact commit or the version.
      # uses: easingthemes/ssh-deploy@3884c8554ff45c0fd37d3f12a76288d06ce7a2ff
      uses: easingthemes/ssh-deploy@v4.1.8
      with:
        # Private key part of an SSH key pair
        SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
        # Remote host
        REMOTE_HOST: ${{secrets.REMOTE_HOST}}
        # Remote user
        REMOTE_USER: ${{secrets.REMOTE_USER}}
        # Source directory, path relative to `$GITHUB_WORKSPACE` root, eg: `dist/`
        SOURCE: ${{ vars.SOURCE }} 
        # Target directory
        TARGET: ${{ vars.TARGET }} 
        
#   deploy:
#     permissions:
#       contents: none
#     runs-on: ubuntu-latest
#     needs: build
#     steps:
    # Deploy
    # - name: ssh deploy
    #   uses: AEnterprise/rsync-deploy@v1.0
    #   env:
    #     DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    #     ARGS: "-e -c -r --delete"
    #     SERVER_PORT: 22
    #     FOLDER: "./public"
    #     SERVER_IP: ${{ secrets.REMOTE_HOST }}
    #     USERNAME: ${{ secrets.REMOTE_USER }}
    #     SERVER_DESTINATION: "www/test-deploy"
    # - name: SSH Server Deploy
    #   uses: kostya-ten/ssh-server-deploy@v4
    #   with:
    #     host: ${{ secrets.REMOTE_HOST }}
    #     port: ${{ secrets.REMOTE_PORT }}
    #     username: ${{ secrets.REMOTE_USER }}
    #     password: ${{ secrets.REMOTE_PASSWORD }}
    #     scp_source: ${{ vars.SOURCE }}
    #     scp_target: ${{ vars.TARGET }}
    #     before_script: |
    #       ls
    #       df -h
    #     after_script: |
    #       whoami
      
