
name: Deploying

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  NODE_VERSION: '18.x'                # set this to the node version to use

permissions: 
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: npm install, build
      run: |
        npm install
        npm run build --if-present
        ls

    - name: Deploy to Server
      uses: hengkx/ssh-deploy@v1.0.1
      with:
        USERNAME: ${{ secrets.REMOTE_USER }}
        PASSWORD: ${{ secrets.REMOTE_PASSWORD }}
        HOST: ${{ secrets.REMOTE_HOST }}
        SOURCE: ${{ vars.SOURCE }}
        TARGET: ${{ vars.TARGET }}
        AFTER_COMMAND: 'node index.js'
  